contact_links:
  - name: Telegram group | Telegram группа
    url: https://t.me/+2lmP1yhxpCE3MDcy
    about: News and releases of the fork | Новости и релизы форка
  - name: Telegram chat | Telegram чат
    url: https://t.me/+8BJQXYXYLqM4YWYy
    about: Community support and discussions | Поддержка сообщества и обсуждения
